name: Adaptive QoS System CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  angular-dashboard:
    name: Angular Dashboard Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./admin-dashboard
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: admin-dashboard/package.json

      - name: Install Dependencies
        run: npm install --no-audit --no-fund

      - name: Build Production
        run: npm run build -- --configuration production

  java-services:
    name: Java Backend Build (Gateway & Core)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build Gateway Service
        run: mvn -B package --file gateway-service/pom.xml

      - name: Build Core Processor
        run: mvn -B package --file core-processor/pom.xml

  python-ml:
    name: ML Inference Engine Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./inference-engine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: inference-engine/requirements.txt

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Generate Proto Code
        run: |
          mkdir -p proto
          python -m grpc_tools.protoc -I../proto --python_out=./proto --grpc_python_out=./proto ../proto/*.proto